"""TerraformExecutor — per-task isolated workspace, plan, apply, state parse."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import textwrap
import threading
from pathlib import Path
from typing import Any

import structlog

from hc.executor.classifier import ErrorClassifier
from hc.executor.models import ExecutionResult, TFState

logger = structlog.get_logger()

# Provider version constraint — bump only via PR that updates all modules atomically.
_PROVIDER_VERSION = "~> 0.3"

_MAIN_TF_TEMPLATE = textwrap.dedent(
    """\
    # Auto-generated by TerraformExecutor — do not edit by hand.
    terraform {{
      required_version = ">= 1.6"
      required_providers {{
        fptcloud = {{
          source  = "fpt-corp/fptcloud"
          version = "{provider_version}"
        }}
      }}
    }}

    provider "fptcloud" {{}}

    {variable_blocks}

    module "this" {{
      source = "{module_source}"
    {module_args}}}

    output "result" {{
      value     = module.this
      sensitive = false
    }}
    """
)


class TerraformExecutorError(Exception):
    """Raised when a terraform subprocess fails in an unrecoverable way."""


class TerraformExecutor:
    """
    Thin wrapper around the Terraform CLI (inspired by python-terraform's interface).

    Each instance owns a single *workspace directory* that is created on first
    ``bootstrap()`` call and optionally deleted after a successful apply.

    All ``FPTCLOUD_*`` env vars are passed to every subprocess via the *env*
    constructor argument — they are **never** written to disk.
    """

    def __init__(
        self,
        workspace_path: str | Path,
        module_path: str | Path,
        vars: dict[str, Any],
        env: dict[str, str] | None = None,
        plugin_cache_dir: str | Path | None = None,
        cleanup_on_success: bool = True,
        timeout_seconds: int = 600,
    ) -> None:
        self._workspace = Path(workspace_path)
        self._module = Path(module_path)
        self._vars = vars
        self._base_env: dict[str, str] = {k: v for k, v in os.environ.items()}
        if env:
            self._base_env.update(env)
        self._plugin_cache = Path(plugin_cache_dir) if plugin_cache_dir else None
        self.cleanup_on_success = cleanup_on_success
        self._timeout = timeout_seconds
        self._classifier = ErrorClassifier()
        self._log = logger.bind(workspace=str(self._workspace), module=str(self._module))

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def bootstrap(self) -> None:
        """Create workspace dir, write main.tf + tfvars.json, run terraform init."""
        self._workspace.mkdir(parents=True, exist_ok=True)
        self._write_main_tf()
        self._write_tfvars()
        self._run_init()

    def plan(self) -> tuple[int, dict[str, Any]]:
        """Run ``terraform plan -out=tfplan -detailed-exitcode``.

        Returns (exit_code, plan_json) where exit_code is:
        - 0: no changes
        - 2: changes pending (expected on first apply)
        Raises TerraformExecutorError for any other exit code.
        """
        rc, stdout, stderr = self._run(
            ["terraform", "plan", "-out=tfplan", "-detailed-exitcode", "-no-color", "-input=false"]
        )
        if rc not in (0, 2):
            error = self._classifier.classify(stderr or stdout)
            raise TerraformExecutorError(
                f"terraform plan failed (rc={rc}) [{error.category}]: {error.message}"
            )

        plan_json: dict[str, Any] = {}
        try:
            _, plan_stdout, _ = self._run(["terraform", "show", "-json", "-no-color", "tfplan"])
            plan_json = json.loads(plan_stdout or "{}")
        except Exception as exc:  # noqa: BLE001
            self._log.warning("plan_show_failed", error=str(exc))

        return rc, plan_json

    def apply_plan(self) -> tuple[int, str, str]:
        """Run ``terraform apply tfplan -auto-approve``."""
        return self._run(
            ["terraform", "apply", "-auto-approve", "-no-color", "-input=false", "tfplan"]
        )

    def show_state(self) -> TFState:
        """Run ``terraform show -json`` and parse into TFState."""
        _, stdout, _ = self._run(["terraform", "show", "-json", "-no-color"])
        data: dict[str, Any] = json.loads(stdout or "{}")
        return TFState.from_json(data)

    def execute(self) -> ExecutionResult:
        """Full pipeline: bootstrap → plan → apply → show → optional cleanup."""
        all_stdout: list[str] = []
        all_stderr: list[str] = []

        # --- bootstrap ---
        try:
            self.bootstrap()
        except Exception as exc:
            classified = self._classifier.classify(str(exc))
            return ExecutionResult(
                success=False,
                stdout="\n".join(all_stdout),
                stderr="\n".join(all_stderr),
                error=classified,
                workspace_path=str(self._workspace),
            )

        # --- plan ---
        plan_rc = -1
        plan_json: dict[str, Any] = {}
        try:
            plan_rc, plan_json = self.plan()
        except TerraformExecutorError as exc:
            classified = self._classifier.classify(str(exc))
            return ExecutionResult(
                success=False,
                plan_exit_code=plan_rc,
                plan_json=plan_json,
                stdout="\n".join(all_stdout),
                stderr="\n".join(all_stderr),
                error=classified,
                workspace_path=str(self._workspace),
            )

        # --- apply ---
        apply_rc, apply_stdout, apply_stderr = self.apply_plan()
        all_stdout.append(apply_stdout)
        all_stderr.append(apply_stderr)

        if apply_rc != 0:
            error = self._classifier.classify(apply_stderr or apply_stdout or "")
            return ExecutionResult(
                success=False,
                plan_exit_code=plan_rc,
                plan_json=plan_json,
                stdout="\n".join(all_stdout),
                stderr="\n".join(all_stderr),
                error=error,
                workspace_path=str(self._workspace),
            )

        # --- show state ---
        tf_state: TFState | None = None
        try:
            tf_state = self.show_state()
        except Exception as exc:  # noqa: BLE001
            self._log.warning("show_state_failed", error=str(exc))

        if self.cleanup_on_success:
            self.cleanup()

        return ExecutionResult(
            success=True,
            plan_exit_code=plan_rc,
            plan_json=plan_json,
            state=tf_state,
            stdout="\n".join(all_stdout),
            stderr="\n".join(all_stderr),
            workspace_path=str(self._workspace),
        )

    def cleanup(self) -> None:
        """Remove the workspace directory."""
        if self._workspace.exists():
            shutil.rmtree(self._workspace, ignore_errors=True)
            self._log.info("workspace_cleaned")

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _write_main_tf(self) -> None:
        variable_lines: list[str] = []
        module_arg_lines: list[str] = []
        for key in sorted(self._vars.keys()):
            variable_lines.append(f'variable "{key}" {{}}')
            module_arg_lines.append(f"  {key} = var.{key}")

        # Normalize path separators for HCL (forward slashes always)
        module_source = str(self._module).replace("\\", "/")

        content = _MAIN_TF_TEMPLATE.format(
            provider_version=_PROVIDER_VERSION,
            variable_blocks="\n".join(variable_lines),
            module_source=module_source,
            module_args="\n".join(module_arg_lines) + "\n" if module_arg_lines else "",
        )
        (self._workspace / "main.tf").write_text(content, encoding="utf-8")
        self._log.debug("main_tf_written", vars=list(self._vars.keys()))

    def _write_tfvars(self) -> None:
        # FPTCLOUD_* credentials must NOT appear here — only infrastructure vars.
        safe_vars = {k: v for k, v in self._vars.items() if not k.upper().startswith("FPTCLOUD_")}
        path = self._workspace / "terraform.tfvars.json"
        path.write_text(json.dumps(safe_vars, indent=2), encoding="utf-8")
        self._log.debug("tfvars_written", keys=list(safe_vars.keys()))

    def _run_init(self) -> None:
        env = dict(self._base_env)
        if self._plugin_cache:
            self._plugin_cache.mkdir(parents=True, exist_ok=True)
            env["TF_PLUGIN_CACHE_DIR"] = str(self._plugin_cache)
        rc, stdout, stderr = self._run(
            ["terraform", "init", "-no-color", "-input=false"],
            env=env,
        )
        if rc != 0:
            raise TerraformExecutorError(f"terraform init failed (rc={rc}):\n{stderr or stdout}")

    def _run(
        self,
        cmd: list[str],
        env: dict[str, str] | None = None,
    ) -> tuple[int, str, str]:
        """Execute a terraform sub-command, streaming output line-by-line to the logger."""
        run_env = env if env is not None else dict(self._base_env)
        self._log.debug("tf_cmd", cmd=" ".join(cmd))

        stdout_lines: list[str] = []
        stderr_lines: list[str] = []

        def _reader(stream: Any, buf: list[str], level: str) -> None:
            for raw in stream:
                line = raw.rstrip("\n")
                buf.append(line)
                self._log.debug(f"tf_{level}", line=line)

        try:
            proc = subprocess.Popen(
                cmd,
                cwd=str(self._workspace),
                env=run_env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except FileNotFoundError as exc:
            raise TerraformExecutorError(
                f"terraform binary not found: {cmd[0]!r} — is Terraform on PATH?"
            ) from exc

        t_out = threading.Thread(
            target=_reader, args=(proc.stdout, stdout_lines, "stdout"), daemon=True
        )
        t_err = threading.Thread(
            target=_reader, args=(proc.stderr, stderr_lines, "stderr"), daemon=True
        )
        t_out.start()
        t_err.start()

        try:
            proc.wait(timeout=self._timeout)
        except subprocess.TimeoutExpired as exc:
            proc.kill()
            t_out.join(timeout=5)
            t_err.join(timeout=5)
            raise TerraformExecutorError(
                f"terraform command timed out after {self._timeout}s: {' '.join(cmd)}"
            ) from exc

        t_out.join()
        t_err.join()

        return proc.returncode, "\n".join(stdout_lines), "\n".join(stderr_lines)
